# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CT ProtoBuf

on:
  push:
    branches: ['master', 'main']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: run tests
        run: tools/src/test/proto/test.sh

  # TODO: check for breaking changes from this commit to master
  # example: https://github.com/DependencyTrack/hyades/blob/main/.github/workflows/buf.yml